/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_RTCRtpReceiver */

#ifndef _Included_io_github_sendablemetatype_webrtc_RTCRtpReceiver
#define _Included_io_github_sendablemetatype_webrtc_RTCRtpReceiver
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpReceiver
	 * Method:    getTrack
	 * Signature: ()Lio/github/sendablemetatype/webrtc/media/MediaStreamTrack;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpReceiver_getTrack
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpReceiver
	 * Method:    getTransport
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCDtlsTransport;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpReceiver_getTransport
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpReceiver
	 * Method:    getParameters
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCRtpParameters;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpReceiver_getParameters
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpReceiver
	 * Method:    getContributingSources
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpReceiver_getContributingSources
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpReceiver
	 * Method:    getSynchronizationSources
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpReceiver_getSynchronizationSources
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
