/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_RTCDtmfSender */

#ifndef _Included_io_github_sendablemetatype_webrtc_RTCDtmfSender
#define _Included_io_github_sendablemetatype_webrtc_RTCDtmfSender
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCDtmfSender
	 * Method:    canInsertDtmf
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_sendablemetatype_webrtc_RTCDtmfSender_canInsertDtmf
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCDtmfSender
	 * Method:    insertDtmf
	 * Signature: (Ljava/lang/String;II)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_sendablemetatype_webrtc_RTCDtmfSender_insertDtmf
	(JNIEnv *, jobject, jstring, jint, jint);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCDtmfSender
	 * Method:    tones
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_io_github_sendablemetatype_webrtc_RTCDtmfSender_tones
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCDtmfSender
	 * Method:    duration
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_io_github_sendablemetatype_webrtc_RTCDtmfSender_duration
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCDtmfSender
	 * Method:    interToneGap
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_io_github_sendablemetatype_webrtc_RTCDtmfSender_interToneGap
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCDtmfSender
	 * Method:    registerObserver
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCDtmfSenderObserver;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCDtmfSender_registerObserver
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCDtmfSender
	 * Method:    unregisterObserver
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCDtmfSender_unregisterObserver
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif