/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
#define _Included_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
	 * Method:    setSourceId
	 * Signature: (JZ)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource_setSourceId
	(JNIEnv*, jobject, jlong, jboolean);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
	 * Method:    setFrameRate
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource_setFrameRate
	(JNIEnv*, jobject, jint);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
	 * Method:    setMaxFrameSize
	 * Signature: (II)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource_setMaxFrameSize
	(JNIEnv*, jobject, jint, jint);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
	 * Method:    setFocusSelectedSource
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource_setFocusSelectedSource
	(JNIEnv*, jobject, jboolean);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
	 * Method:    start
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource_start
	(JNIEnv*, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
	 * Method:    stop
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource_stop
	(JNIEnv*, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource_dispose
	(JNIEnv*, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoDesktopSource_initialize
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
