/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer
#define _Included_io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer
	 * Method:    allocate
	 * Signature: (II)Lio/github/sendablemetatype/webrtc/media/video/NativeI420Buffer;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer_allocate
	(JNIEnv *, jclass, jint, jint);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer
	 * Method:    copy
	 * Signature: (IILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)Lio/github/sendablemetatype/webrtc/media/video/NativeI420Buffer;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer_copy
	(JNIEnv*, jclass, jint, jint, jobject, jint, jobject, jint, jobject, jint);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer
	 * Method:    cropAndScale
	 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIIIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;III)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_NativeI420Buffer_cropAndScale
	(JNIEnv *, jclass, jobject, jint, jobject, jint, jobject, jint, jint, jint, jint, jint, jobject, jint, jobject, jint, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
