/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_PeerConnectionFactory */

#ifndef _Included_io_github_sendablemetatype_webrtc_PeerConnectionFactory
#define _Included_io_github_sendablemetatype_webrtc_PeerConnectionFactory
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_PeerConnectionFactory
	 * Method:    createAudioSource
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/audio/AudioOptions;)Lio/github/sendablemetatype/webrtc/media/audio/AudioTrackSource;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_PeerConnectionFactory_createAudioSource
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_PeerConnectionFactory
	 * Method:    createAudioTrack
	 * Signature: (Ljava/lang/String;Lio/github/sendablemetatype/webrtc/media/audio/AudioTrackSource;)Lio/github/sendablemetatype/webrtc/media/audio/AudioTrack;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_PeerConnectionFactory_createAudioTrack
	(JNIEnv *, jobject, jstring, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_PeerConnectionFactory
	 * Method:    createVideoTrack
	 * Signature: (Ljava/lang/String;Lio/github/sendablemetatype/webrtc/media/video/VideoTrackSource;)Lio/github/sendablemetatype/webrtc/media/video/VideoTrack;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_PeerConnectionFactory_createVideoTrack
	(JNIEnv *, jobject, jstring, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_PeerConnectionFactory
	 * Method:    createPeerConnection
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCConfiguration;Lio/github/sendablemetatype/webrtc/PeerConnectionObserver;)Lio/github/sendablemetatype/webrtc/RTCPeerConnection;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_PeerConnectionFactory_createPeerConnection
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_PeerConnectionFactory
	 * Method:    getRtpReceiverCapabilities
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/MediaType;)Lio/github/sendablemetatype/webrtc/RTCRtpCapabilities;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_PeerConnectionFactory_getRtpReceiverCapabilities
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_PeerConnectionFactory
	 * Method:    getRtpSenderCapabilities
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/MediaType;)Lio/github/sendablemetatype/webrtc/RTCRtpCapabilities;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_PeerConnectionFactory_getRtpSenderCapabilities
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_PeerConnectionFactory
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_PeerConnectionFactory_dispose
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_PeerConnectionFactory
	 * Method:    initialize
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/audio/AudioDeviceModule;Lio/github/sendablemetatype/webrtc/media/audio/AudioProcessing;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_PeerConnectionFactory_initialize
	(JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
