/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_MediaSource */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_MediaSource
#define _Included_io_github_sendablemetatype_webrtc_media_MediaSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaSource
	 * Method:    getState
	 * Signature: ()Lio/github/sendablemetatype/webrtc/media/MediaSource/State;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaSource_getState
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
