/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_video_desktop_ScreenSaver */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_video_desktop_ScreenSaver
#define _Included_io_github_sendablemetatype_webrtc_media_video_desktop_ScreenSaver
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     io_github_sendablemetatype_webrtc_media_video_desktop_PowerManagement
     * Method:    enableUserActivity
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_desktop_PowerManagement_enableUserActivity
      (JNIEnv *, jobject);

    /*
     * Class:     io_github_sendablemetatype_webrtc_media_video_desktop_PowerManagement
     * Method:    disableUserActivity
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_desktop_PowerManagement_disableUserActivity
      (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
