/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_RTCRtpSender */

#ifndef _Included_io_github_sendablemetatype_webrtc_RTCRtpSender
#define _Included_io_github_sendablemetatype_webrtc_RTCRtpSender
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpSender
	 * Method:    getTrack
	 * Signature: ()Lio/github/sendablemetatype/webrtc/media/MediaStreamTrack;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpSender_getTrack
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpSender
	 * Method:    getTransport
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCDtlsTransport;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpSender_getTransport
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpSender
	 * Method:    replaceTrack
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/MediaStreamTrack;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpSender_replaceTrack
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpSender
	 * Method:    setParameters
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCRtpSendParameters;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpSender_setParameters
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpSender
	 * Method:    getParameters
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCRtpSendParameters;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpSender_getParameters
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpSender
	 * Method:    setStreams
	 * Signature: (Ljava/util/List;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpSender_setStreams
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCRtpSender
	 * Method:    getDtmfSender
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCDtmfSender;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCRtpSender_getDtmfSender
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
