/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_internal_RefCountedObject */

#ifndef _Included_io_github_sendablemetatype_webrtc_internal_RefCountedObject
#define _Included_io_github_sendablemetatype_webrtc_internal_RefCountedObject
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_internal_RefCountedObject
	 * Method:    retain
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_internal_RefCountedObject_retain
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_internal_RefCountedObject
	 * Method:    release
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_internal_RefCountedObject_release
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
