/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_MediaDevices */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_MediaDevices
#define _Included_io_github_sendablemetatype_webrtc_media_MediaDevices
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaDevices
	 * Method:    addDeviceChangeListener
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/DeviceChangeListener;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaDevices_addDeviceChangeListener
	(JNIEnv*, jclass, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaDevices
	 * Method:    removeDeviceChangeListener
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/DeviceChangeListener;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaDevices_removeDeviceChangeListener
	(JNIEnv*, jclass, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaDevices
	 * Method:    getDefaultAudioRenderDevice
	 * Signature: ()Lio/github/sendablemetatype/webrtc/media/audio/AudioDevice;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaDevices_getDefaultAudioRenderDevice
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaDevices
	 * Method:    getDefaultAudioCaptureDevice
	 * Signature: ()Lio/github/sendablemetatype/webrtc/media/audio/AudioDevice;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaDevices_getDefaultAudioCaptureDevice
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaDevices
	 * Method:    getAudioRenderDevices
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaDevices_getAudioRenderDevices
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaDevices
	 * Method:    getAudioCaptureDevices
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaDevices_getAudioCaptureDevices
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaDevices
	 * Method:    getVideoCaptureDevices
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaDevices_getVideoCaptureDevices
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_MediaDevices
	 * Method:    getVideoCaptureCapabilities
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/video/VideoDevice;)Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_media_MediaDevices_getVideoCaptureCapabilities
	(JNIEnv*, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
