/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_video_VideoTrackSource */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_video_VideoTrackSource
#define _Included_io_github_sendablemetatype_webrtc_media_video_VideoTrackSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoTrackSource
	 * Method:    setVideoProcessorNative
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/video/VideoProcessor;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoTrackSource_setVideoProcessorNative
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_VideoTrackSource
	 * Method:    deliverProcessedFrame
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/video/VideoFrame;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_VideoTrackSource_deliverProcessedFrame
	(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
