/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_audio_AudioResampler */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_audio_AudioResampler
#define _Included_io_github_sendablemetatype_webrtc_media_audio_AudioResampler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_audio_AudioResampler
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_AudioResampler_dispose
	(JNIEnv*, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_audio_AudioResampler
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_AudioResampler_initialize
	(JNIEnv*, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_audio_AudioResampler
	 * Method:    resample
	 * Signature: ([BI[BII)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_AudioResampler_resampleInternal
	(JNIEnv*, jobject, jbyteArray, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
