/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_video_desktop_WindowCapturer */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_video_desktop_WindowCapturer
#define _Included_io_github_sendablemetatype_webrtc_media_video_desktop_WindowCapturer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_video_desktop_WindowCapturer
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_video_desktop_WindowCapturer_initialize
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
