/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector
#define _Included_io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector
     * Method:    process
     * Signature: ([BII)V
     */
    JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector_process
      (JNIEnv *, jobject, jbyteArray, jint, jint);

    /*
     * Class:     io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector
     * Method:    getLastVoiceProbability
     * Signature: ()F
     */
    JNIEXPORT jfloat JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector_getLastVoiceProbability
      (JNIEnv *, jobject);

    /*
     * Class:     io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector
     * Method:    dispose
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector_dispose
      (JNIEnv *, jobject);

    /*
     * Class:     io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector
     * Method:    initialize
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_VoiceActivityDetector_initialize
      (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif