/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_RTCPeerConnection */

#ifndef _Included_io_github_sendablemetatype_webrtc_RTCPeerConnection
#define _Included_io_github_sendablemetatype_webrtc_RTCPeerConnection
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getSenders
	 * Signature: ()[Lio/github/sendablemetatype/webrtc/RTCRtpSender;
	 */
	JNIEXPORT jobjectArray JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getSenders
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getReceivers
	 * Signature: ()[Lio/github/sendablemetatype/webrtc/RTCRtpReceiver;
	 */
	JNIEXPORT jobjectArray JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getReceivers
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getTransceivers
	 * Signature: ()[Lio/github/sendablemetatype/webrtc/RTCRtpTransceiver;
	 */
	JNIEXPORT jobjectArray JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getTransceivers
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    addTrack
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/MediaStreamTrack;Ljava/util/List;)Lio/github/sendablemetatype/webrtc/RTCRtpSender;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_addTrack
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    removeTrack
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCRtpSender;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_removeTrack
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    addTransceiver
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/MediaStreamTrack;Lio/github/sendablemetatype/webrtc/RTCRtpTransceiverInit;)Lio/github/sendablemetatype/webrtc/RTCRtpTransceiver;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_addTransceiver
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    createDataChannel
	 * Signature: (Ljava/lang/String;Lio/github/sendablemetatype/webrtc/RTCDataChannelInit;)Lio/github/sendablemetatype/webrtc/RTCDataChannel;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_createDataChannel
	(JNIEnv *, jobject, jstring, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    createOffer
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCOfferOptions;Lio/github/sendablemetatype/webrtc/CreateSessionDescriptionObserver;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_createOffer
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    createAnswer
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCAnswerOptions;Lio/github/sendablemetatype/webrtc/CreateSessionDescriptionObserver;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_createAnswer
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getCurrentLocalDescription
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCSessionDescription;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getCurrentLocalDescription
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getLocalDescription
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCSessionDescription;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getLocalDescription
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getPendingLocalDescription
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCSessionDescription;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getPendingLocalDescription
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getCurrentRemoteDescription
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCSessionDescription;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getCurrentRemoteDescription
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getRemoteDescription
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCSessionDescription;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getRemoteDescription
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getPendingRemoteDescription
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCSessionDescription;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getPendingRemoteDescription
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    setLocalDescription
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCSessionDescription;Lio/github/sendablemetatype/webrtc/SetSessionDescriptionObserver;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_setLocalDescription
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    setRemoteDescription
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCSessionDescription;Lio/github/sendablemetatype/webrtc/SetSessionDescriptionObserver;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_setRemoteDescription
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    addIceCandidate
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCIceCandidate;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_addIceCandidate
	(JNIEnv *, jobject, jobject);

	/*
	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getSignalingState
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCSignalingState;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getSignalingState
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getIceGatheringState
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCIceGatheringState;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getIceGatheringState
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getIceConnectionState
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCIceConnectionState;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getIceConnectionState
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getConnectionState
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCPeerConnectionState;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getConnectionState
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getConfiguration
	 * Signature: ()Lio/github/sendablemetatype/webrtc/RTCConfiguration;
	 */
	JNIEXPORT jobject JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getConfiguration
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    setConfiguration
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCConfiguration;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_setConfiguration
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getStats
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCStatsCollectorCallback;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getStats__Lio_github_sendablemetatype_webrtc_RTCStatsCollectorCallback_2
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getStats
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCRtpReceiver;Lio/github/sendablemetatype/webrtc/RTCStatsCollectorCallback;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getStats__Lio_github_sendablemetatype_webrtc_RTCRtpReceiver_2Lio_github_sendablemetatype_webrtc_RTCStatsCollectorCallback_2
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    getStats
	 * Signature: (Lio/github/sendablemetatype/webrtc/RTCRtpSender;Lio/github/sendablemetatype/webrtc/RTCStatsCollectorCallback;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_getStats__Lio_github_sendablemetatype_webrtc_RTCRtpSender_2Lio_github_sendablemetatype_webrtc_RTCStatsCollectorCallback_2
	(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    restartIce
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_restartIce
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_RTCPeerConnection
	 * Method:    close
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_RTCPeerConnection_close
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
