/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource */

#ifndef _Included_io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource
#define _Included_io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource_initialize
	(JNIEnv *, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource
	 * Method:    initializeWithClock
	 * Signature: (Lio/github/sendablemetatype/webrtc/media/SyncClock;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource_initializeWithClock
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource_dispose
	(JNIEnv*, jobject);

	/*
	 * Class:     io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource
	 * Method:    pushAudio
	 * Signature: ([BIIII)V
	 */
	JNIEXPORT void JNICALL Java_io_github_sendablemetatype_webrtc_media_audio_CustomAudioSource_pushAudio
	(JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif